apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
spec:
  generators:
    - git:
        repoURL: &url https://github.com/tom-stockwell/validated-patterns-example.git
        revision: &rev HEAD
        directories:
          - path: clusters/hub/*
  template:
    spec:
      source:
        repoURL: *url
        targetRevision: *rev
        path: '{{ path }}'
