apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: dev.sandbox1467.opentlc.com
          role: dev.sandbox1467.opentlc.com-role
