apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/tom-stockwell/validated-patterns//patterns/multicloud-gitops/hub
  - openshift-gitops

components:
  - ../../../components/vault-server

patches:
  - path: policy-cluster-config.patch.yml
    target:
      kind: Policy
      name: cluster-config-applicationset

